Structure & Navbar
jelin-mi/pirinexus-route pull request #21
Opened 2022-05-16 20:25 UTC by jandcreative

1. React Router Library
2. Navbar Component
3. Update general CSS

2022-05-17 20:55 UTC, jelin-mi commented on src/App.css
> +  font-family: 'Rubik',sans-serif;
Add a space after a comma, thanks.

2022-05-17 21:23 UTC, jelin-mi requested changes
Please adjust the code as per my comments, just minor things.
Thanks!

2022-05-17 21:23 UTC, jelin-mi commented on src/App.js
> +import './Reset.css';
Just an idea, I would move App.css right above Reset.css in the line 7.

2022-05-17 21:23 UTC, jelin-mi commented on src/App.css
> +  font-family: 'Rubik',sans-serif;
```suggestion
  font-family: 'Rubik', sans-serif;
```
Add a space after a comma, thanks.

2022-05-17 21:23 UTC, jelin-mi commented on src/App.js
>  import "./App.css";
Do not add empty files as those are not uploaded and it causes errors. Or maybe you forgot to push your last changes?

> Failed to compile.
> 
> Module not found: Error: Can't resolve './pages/Home/Home.jsx' in '/Users/michaela/code/pirinexus-route/pirinexus-route/src'
> ERROR in ./src/App.js 6:0-41
> Module not found: Error: Can't resolve './pages/Home/Home.jsx' in '/Users/michaela/code/pirinexus-route/pirinexus-route/src'
> 
> ERROR in ./src/App.js 7:0-47
> Module not found: Error: Can't resolve './pages/Tracks/Tracks.jsx' in '/Users/michaela/code/pirinexus-route/pirinexus-route/src'
> 
> ERROR in ./src/App.js 8:0-47
> Module not found: Error: Can't resolve './pages/Bikers/Bikers.jsx' in '/Users/michaela/code/pirinexus-route/pirinexus-route/src'
> 
> ERROR in ./src/App.js 9:0-44
> Module not found: Error: Can't resolve './pages/Error/Error.jsx' in '/Users/michaela/code/pirinexus-route/pirinexus-route/src'
> 
> webpack compiled with 4 errors

2022-05-17 21:23 UTC, jelin-mi commented on src/components/Navbar/Navbar.css
> +/* Navbar */
Run `Format Document` before pushing your code, please.

2022-05-17 21:23 UTC, jelin-mi commented on src/components/Navbar/Navbar.jsx
> +import { NavLink } from "react-router-dom";
Run `Format Document` before pushing your code, please.

2022-05-18 15:24 UTC, jandcreative commented on src/components/Navbar/Navbar.jsx
> +import { NavLink } from "react-router-dom";
Corrected

2022-05-18 15:39 UTC, jandcreative commented on src/App.css
> +  font-family: 'Rubik',sans-serif;
Corrected!

2022-05-18 17:40 UTC, jelin-mi approved these changes
Ready to be merged to `develop`!

2022-05-18 17:43 UTC, merged